<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Models\"/>
        <Folder Include="Scr\Events\"/>
        <Content Include="Assets\Localization\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Include="Assets\Jsons\temp_apps.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="Assets\avalonia-logo.ico">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <AvaloniaResource Include="Assets\**"/>
        <None Include="Libs/steam_api64.dll" CopyToOutputDirectory="Always">
            <Link>steam_api64.dll</Link>
        </None>

        <None Include="Libs/libsteam_api.so" CopyToOutputDirectory="Always">
            <Link>libsteam_api.so</Link>
        </None>

        <None Include="Libs/steam_appid.txt" CopyToOutputDirectory="Always">
            <Link>steam_appid.txt</Link>
        </None>
        <None Include="Libs/libsteam_api.so">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <TargetPath>runtimes/linux-x64/native/libsteam_api.so</TargetPath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Autofac" Version="8.4.0"/>
        <PackageReference Include="Avalonia" Version="11.3.11"/>
        <PackageReference Include="Avalonia.BuildServices" Version="11.3.2"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Remote.Protocol" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Labs.Gif" Version="11.3.1" />

        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0-rc.1.25451.107"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0-rc.1.25451.107">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0-rc.1"/>
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Include="Steamworks.NET" Version="2024.8.0"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\MainWindow\GameTable.axaml.cs">
            <DependentUpon>GameTable.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MainWindow\MainWindow.axaml.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MainWindow\MainWindowContent.axaml.cs">
            <DependentUpon>MainWindowContent.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MainWindow\ProfileContent.axaml.cs">
            <DependentUpon>ProfileContent.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MainWindow\RollGame.axaml.cs">
            <DependentUpon>RollGame.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MainWindow\Rules.axaml.cs">
            <DependentUpon>Rules.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\LobbyWindow.axaml.cs">
            <DependentUpon>LobbyWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ErrorWindow.axaml.cs">
            <DependentUpon>ErrorWindow.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\ConfirmFinishGame.axaml.cs">
          <DependentUpon>ConfirmFinishGame.axaml</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MessageBox\MessageBox.csproj"/>
    </ItemGroup>
</Project>
