// <auto-generated />
using System;
using GameRandom.DataBaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameRandom.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219061121_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameRandom.DataBaseContexts.GameProgress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AppID")
                        .HasColumnType("integer");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PlayerID")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ID");

                    b.ToTable("GameProgresses");
                });

            modelBuilder.Entity("GameRandom.DataBaseContexts.Lobby", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<long>("LobbyID")
                        .HasColumnType("bigint");

                    b.Property<int>("MembersCount")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("GameRandom.DataBaseContexts.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AvatarURL")
                        .HasColumnType("integer");

                    b.Property<long>("LobbyID")
                        .HasColumnType("bigint");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SteamID")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameRandom.DataBaseContexts.UserGame", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("BeginData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHaveGame")
                        .HasColumnType("boolean");

                    b.Property<int>("LeftDays")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("GameID")
                        .IsUnique();

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("GameRandom.DataBaseContexts.UserGame", b =>
                {
                    b.HasOne("GameRandom.DataBaseContexts.GameProgress", "GameProgress")
                        .WithOne()
                        .HasForeignKey("GameRandom.DataBaseContexts.UserGame", "GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
