// <auto-generated />
using System;
using GameRandom.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameRandom.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708110706_MergeToBaseEntity")]
    partial class MergeToBaseEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameRandom.DbContext.Admins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTopAdmin")
                        .HasColumnType("boolean");

                    b.Property<long?>("LobbiesLobbyId")
                        .HasColumnType("bigint");

                    b.Property<long>("LobbyId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SteamId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("LobbiesLobbyId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GameRandom.DbContext.FinishedGames", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameProgressId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsImprove")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("ScreenShot")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("GameProgressId")
                        .IsUnique();

                    b.ToTable("FinishedGames");
                });

            modelBuilder.Entity("GameRandom.DbContext.GameProgresses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AppHeaderImage")
                        .HasColumnType("bytea");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<string>("AppName")
                        .HasColumnType("text");

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PlayerId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("GameProgresses");
                });

            modelBuilder.Entity("GameRandom.DbContext.Lobbies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("LobbyId")
                        .HasColumnType("bigint");

                    b.Property<int>("MembersCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("GameRandom.DbContext.LobbyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("LobbyId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.ToTable("LobbyData");
                });

            modelBuilder.Entity("GameRandom.DbContext.UserGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<string>("AppIdList")
                        .HasColumnType("text");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("GameRandom.DbContext.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvatarURL")
                        .HasColumnType("integer");

                    b.Property<long>("LobbyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<decimal>("SteamId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameRandom.DbContext.Admins", b =>
                {
                    b.HasOne("GameRandom.DbContext.Lobbies", null)
                        .WithMany("AdminsList")
                        .HasForeignKey("LobbiesLobbyId")
                        .HasPrincipalKey("LobbyId");
                });

            modelBuilder.Entity("GameRandom.DbContext.FinishedGames", b =>
                {
                    b.HasOne("GameRandom.DbContext.GameProgresses", "GameProgresses")
                        .WithMany()
                        .HasForeignKey("GameProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProgresses");
                });

            modelBuilder.Entity("GameRandom.DbContext.LobbyData", b =>
                {
                    b.HasOne("GameRandom.DbContext.Lobbies", null)
                        .WithMany("LobbyData")
                        .HasForeignKey("LobbyId")
                        .HasPrincipalKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameRandom.DbContext.Lobbies", b =>
                {
                    b.Navigation("AdminsList");

                    b.Navigation("LobbyData");
                });
#pragma warning restore 612, 618
        }
    }
}
