// <auto-generated />
using System;
using GameRandom.DataBaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameRandom.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameRandom.DataBaseContexts.GameProgresses", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AppID")
                        .HasColumnType("integer");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PlayerID")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ID");

                    b.ToTable("GameProgresses");
                });

            modelBuilder.Entity("GameRandom.DataBaseContexts.Lobbies", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<long>("LobbyId")
                        .HasColumnType("bigint");

                    b.Property<int>("MembersCount")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("GameRandom.DataBaseContexts.LobbyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("LobbyId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.ToTable("LobbyData");
                });

            modelBuilder.Entity("GameRandom.DataBaseContexts.UserGame", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ID");

                    b.HasIndex("AppId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("GameRandom.DataBaseContexts.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AvatarURL")
                        .HasColumnType("integer");

                    b.Property<long>("LobbyID")
                        .HasColumnType("bigint");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SteamID")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameRandom.DataBaseContexts.LobbyData", b =>
                {
                    b.HasOne("GameRandom.DataBaseContexts.Lobbies", null)
                        .WithMany("LobbyData")
                        .HasForeignKey("LobbyId")
                        .HasPrincipalKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameRandom.DataBaseContexts.UserGame", b =>
                {
                    b.HasOne("GameRandom.DataBaseContexts.GameProgresses", "GameProgresses")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .HasPrincipalKey("AppID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProgresses");
                });

            modelBuilder.Entity("GameRandom.DataBaseContexts.Lobbies", b =>
                {
                    b.Navigation("LobbyData");
                });
#pragma warning restore 612, 618
        }
    }
}
